//
//  MentorsScreenPresenter.swift
//  ITmentors
//
//  Created by Vladimir Alecseev on 27.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MentorsScreenPresentationLogic {
    func presentMentors(response: MentorsScreen.ShowMentorCells.Response)
}

class MentorsScreenPresenter: MentorsScreenPresentationLogic {
    
    weak var viewController: MentorsScreenDisplayLogic?
    
    // MARK: Do something
    
    func presentMentors(response: MentorsScreen.ShowMentorCells.Response) {
        var rows: [MentorsScreen.ShowMentorCells.ViewModel.MentorCellViewModel] = []
        response.mentorCellsData.forEach { mentor in
            rows.append(MentorsScreen.ShowMentorCells.ViewModel.MentorCellViewModel(cellData: mentor))
        }
        let viewModel = MentorsScreen.ShowMentorCells.ViewModel(rows: rows)
        viewController?.displayMentorCells(viewModel: viewModel)
    }
}
