//
//  MentorsScreenInteractor.swift
//  ITmentors
//
//  Created by Vladimir Alecseev on 27.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MentorsScreenBusinessLogic {
    func loadMentors()
}

protocol MentorsScreenDataStore {
    //var name: String { get set }
}

class MentorsScreenInteractor: MentorsScreenBusinessLogic, MentorsScreenDataStore {
    
    var presenter: MentorsScreenPresentationLogic?
    var worker: MentorsScreenWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func loadMentors() {
        worker = MentorsScreenWorker()
        worker?.doSomeWork()
        
        
        //fake data
        var array: [MentorCellModel] = []
        let lala: MentorCellModel = MentorCellModel(name: "Vladimir", discription: "Помогаю со входом в IOS разработку. Пишите в тг", shortDiscription: "Senior IOS dev =(", imageData: UIImage(named: "myPhoto")?.pngData(), languages: [.swift, .ruby, .cPlusPlus, .js, .php, .python], messageLink: "https://t.me/escaping_closure")
        array.append(lala)
        //.swift, .ruby, .cPlusPlus, .js, .php, .python
//        array.append(lala)
//        array.append(lala)

        
        let response = MentorsScreen.ShowMentorCells.Response(mentorCellsData: array)
        presenter?.presentMentors(response: response)
    }
}
