//
//  ProfileScreenModels.swift
//  ITmentors
//
//  Created by Vladimir Alecseev on 27.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProfileScreen {
    // MARK: Use cases
    
    enum Something {
        struct Response {
            var isSignedInWithApple: Bool?
            var isYourInfoFilled: Bool?
        }
        
        struct ViewModel {
            var viewControllerWeNeedToShow: UIViewController
        }
    }
}
