//
//  ProfileScreenViewController.swift
//  ITmentors
//
//  Created by Vladimir Alecseev on 27.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileScreenDisplayLogic: AnyObject {
    func displaySomething(viewModel: ProfileScreen.Something.ViewModel)
}

class ProfileScreenViewController: UIViewController, ProfileScreenDisplayLogic {
    
    //@IBOutlet private var nameTextField: UITextField!
    
    var interactor: ProfileScreenBusinessLogic?
    var router: (NSObjectProtocol & ProfileScreenRoutingLogic & ProfileScreenDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        ProfileMentorConfigurator.shared.configure(with: self)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        ProfileMentorConfigurator.shared.configure(with: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        showRegistationScreenIfNeeded()
        view.backgroundColor = .AppPalette.backgroundColor
    }
    
    
    // MARK: Do something
    
    func showRegistationScreenIfNeeded() {
//        let request = ProfileScreen.Something.Request()
        interactor?.showAuthScreenIfNeeded()
    }
    
    func displaySomething(viewModel: ProfileScreen.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
