//
//  ProfileScreenRouter.swift
//  ITmentors
//
//  Created by Vladimir Alecseev on 27.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileScreenRoutingLogic {
    func navigateToSingInViewController(source: ProfileScreenViewController, destination: SignInWithAppleViewController)
    func navigateToFillDataViewController(source: ProfileScreenViewController, destination: BecomeMentorViewController)
    func navigateToEditDataViewController(source: ProfileScreenViewController, destination: BecomeMentorViewController, withData: ProfileScreen.loadYourDataa.ViewModel)

}

protocol ProfileScreenDataPassing {
    var dataStore: ProfileScreenDataStore? { get }
}

class ProfileScreenRouter: NSObject, ProfileScreenRoutingLogic, ProfileScreenDataPassing {
    
    weak var viewController: ProfileScreenViewController?
    var dataStore: ProfileScreenDataStore?
    
    // MARK: Routing
    
    //func routeToSomewhere(segue: UIStoryboardSegue?) {
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    //MARK: Navigation
    
    func navigateToSingInViewController(source: ProfileScreenViewController, destination: SignInWithAppleViewController) {
      source.show(destination, sender: nil)
    }
    func navigateToFillDataViewController(source: ProfileScreenViewController, destination: BecomeMentorViewController) {
      source.show(destination, sender: nil)
    }
    func navigateToEditDataViewController(source: ProfileScreenViewController, destination: BecomeMentorViewController, withData: ProfileScreen.loadYourDataa.ViewModel) {
        destination.isBackButtonHidden = false
        destination.isItDataEditingScreen = true
        guard var detailDS = destination.router?.dataStore else {return}
        passDataToSomewhere(source: withData, destination: &detailDS)
        destination.isBackButtonHidden = false
        destination.isItDataEditingScreen = true
    source.show(destination, sender: nil)
}
    // MARK: Passing data
    
    func passDataToSomewhere(source: ProfileScreen.loadYourDataa.ViewModel, destination: inout BecomeMentorDataStore) {
        destination.name = source.name
        destination.languages = source.languages
        destination.shortDiscription = source.shortDiscription
        destination.discription = source.discription
        destination.messageLink = source.messageLink
        destination.imageData = source.imageData
    }
}
