//
//  BecomeMentorPresenter.swift
//  ITmentors
//
//  Created by Vladimir Alecseev on 30.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BecomeMentorPresentationLogic {
    func presentSomething(response: BecomeMentor.LoadDataOnServer.Response)
}

class BecomeMentorPresenter: BecomeMentorPresentationLogic {
    
    weak var viewController: BecomeMentorDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: BecomeMentor.LoadDataOnServer.Response) {
        let viewModel = BecomeMentor.LoadDataOnServer.ViewModel(isSuccesed: response.isSuccesed)
        viewController?.displayCompletion(viewModel: viewModel)
    }
}
