//
//  BecomeMentorInteractor.swift
//  ITmentors
//
//  Created by Vladimir Alecseev on 30.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BecomeMentorBusinessLogic {
    func doSomething(request: BecomeMentor.LoadDataOnServer.Request)
}

protocol BecomeMentorDataStore {
    //var name: String { get set }
}

class BecomeMentorInteractor: BecomeMentorBusinessLogic, BecomeMentorDataStore {
    
    var presenter: BecomeMentorPresentationLogic?
    var worker: BecomeMentorWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: BecomeMentor.LoadDataOnServer.Request) {
        worker = BecomeMentorWorker()
        worker?.doSomeWork()
        
        let response = BecomeMentor.LoadDataOnServer.Response()
        presenter?.presentSomething(response: response)
    }
}
