//
//  BecomeMentorPresenter.swift
//  ITmentors
//
//  Created by Vladimir Alecseev on 30.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BecomeMentorPresentationLogic {
    func presentIsSuccessed(response: BecomeMentor.LoadDataOnServer.Response)
    func presentYourData(response: BecomeMentor.TransferDataFromProfileToEditScreen.Response)
}

class BecomeMentorPresenter: BecomeMentorPresentationLogic {
    
    weak var viewController: BecomeMentorDisplayLogic?
    
    // MARK: Do something
    
    func presentIsSuccessed(response: BecomeMentor.LoadDataOnServer.Response) {
        let viewModel = BecomeMentor.LoadDataOnServer.ViewModel(isSuccesed: response.isSuccesed)
        viewController?.displayCompletion(viewModel: viewModel)
    }
    
    func presentYourData(response: BecomeMentor.TransferDataFromProfileToEditScreen.Response) {
        let name = response.name
        let discription = response.discription
        let shortDescription = response.shortDiscription
        let imageData = response.imageData
        let languages = response.languages
        let messageLink = response.messageLink
        let viewModel = BecomeMentor.TransferDataFromProfileToEditScreen.ViewModel(name: name, discription: discription, imageData: imageData, languages: languages, messageLink: messageLink, shortDiscription: shortDescription)

        viewController?.pasteDataFromProfile(viewMode: viewModel)
    }

}
